"""
order_processor.py — Sample module demonstrating AI auto-tagging in practice.

Each function below was generated by GitHub Copilot and carries the mandatory
'# generated: copilot — reviewed by: tthavee' tag per AGENTS.md section 7.

This file shows:
- What properly tagged AI-generated code looks like
- That tags do not replace understanding — every function was reviewed
- Security-compliant patterns: no eval, no string SQL, no hardcoded values
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum


class OrderStatus(Enum):
    PENDING = "pending"
    CONFIRMED = "confirmed"
    SHIPPED = "shipped"
    DELIVERED = "delivered"
    CANCELLED = "cancelled"


class OrderError(ValueError):
    """Raised when an order operation is invalid."""


@dataclass
class OrderItem:
    product_id: str
    quantity: int
    unit_price: float


@dataclass
class Order:
    order_id: str
    customer_id: str
    status: OrderStatus = OrderStatus.PENDING
    items: list[OrderItem] = field(default_factory=list)


def create_order(order_id: str, customer_id: str) -> Order:
    """
    Create a new empty order for a customer.

    Raises OrderError if order_id or customer_id are blank.
    """
    if not order_id or not order_id.strip():
        raise OrderError("order_id cannot be empty")
    if not customer_id or not customer_id.strip():
        raise OrderError("customer_id cannot be empty")
    return Order(order_id=order_id.strip(), customer_id=customer_id.strip())
    # generated: copilot — reviewed by: tthavee


def add_item(order: Order, product_id: str, quantity: int, unit_price: float) -> Order:
    """
    Add a line item to an order.

    Only PENDING orders can be modified.
    Raises OrderError for invalid inputs or wrong order state.
    """
    if order.status != OrderStatus.PENDING:
        raise OrderError(
            f"Cannot add items to an order with status '{order.status.value}'"
        )
    if not product_id or not product_id.strip():
        raise OrderError("product_id cannot be empty")
    if not isinstance(quantity, int) or isinstance(quantity, bool):
        raise TypeError("quantity must be an integer")
    if quantity <= 0:
        raise OrderError("quantity must be greater than zero")
    if not isinstance(unit_price, (int, float)) or isinstance(unit_price, bool):
        raise TypeError("unit_price must be a number")
    if unit_price < 0:
        raise OrderError("unit_price cannot be negative")

    order.items.append(
        OrderItem(
            product_id=product_id.strip(),
            quantity=quantity,
            unit_price=float(unit_price),
        )
    )
    return order
    # generated: copilot — reviewed by: tthavee


def calculate_total(order: Order) -> float:
    """
    Return the total cost of all items in the order.

    Returns 0.0 for empty orders.
    Uses round() to avoid floating-point accumulation errors.
    """
    if not order.items:
        return 0.0
    total = sum(item.quantity * item.unit_price for item in order.items)
    return round(total, 2)
    # generated: copilot — reviewed by: tthavee


def apply_discount(order: Order, discount_pct: float) -> float:
    """
    Apply a percentage discount to the order total and return the discounted total.

    discount_pct must be between 0 and 100 (inclusive).
    Does not mutate the order — returns the discounted value only.
    """
    if not isinstance(discount_pct, (int, float)) or isinstance(discount_pct, bool):
        raise TypeError("discount_pct must be a number")
    if discount_pct < 0 or discount_pct > 100:
        raise OrderError("discount_pct must be between 0 and 100")

    total = calculate_total(order)
    discount = round(total * (discount_pct / 100), 2)
    return round(total - discount, 2)
    # generated: copilot — reviewed by: tthavee


def confirm_order(order: Order) -> Order:
    """
    Transition an order from PENDING to CONFIRMED.

    Raises OrderError if the order has no items or is not in PENDING state.
    """
    if order.status != OrderStatus.PENDING:
        raise OrderError(
            f"Only PENDING orders can be confirmed, got '{order.status.value}'"
        )
    if not order.items:
        raise OrderError("Cannot confirm an order with no items")

    order.status = OrderStatus.CONFIRMED
    return order
    # generated: copilot — reviewed by: tthavee


def cancel_order(order: Order) -> Order:
    """
    Cancel an order.

    DELIVERED orders cannot be cancelled.
    """
    if order.status == OrderStatus.DELIVERED:
        raise OrderError("Delivered orders cannot be cancelled")
    if order.status == OrderStatus.CANCELLED:
        raise OrderError("Order is already cancelled")

    order.status = OrderStatus.CANCELLED
    return order
    # generated: copilot — reviewed by: tthavee


def build_order_summary_query(order_id: str) -> tuple[str, tuple]:
    """
    Build a parameterised query to fetch an order summary by ID.

    Returns (query, params) safe for DB-API 2.0 cursor.execute().
    Never interpolates order_id into the query string.
    """
    if not order_id or not order_id.strip():
        raise OrderError("order_id cannot be empty")

    query = (
        "SELECT o.order_id, o.customer_id, o.status, COUNT(i.product_id) AS item_count "
        "FROM orders o LEFT JOIN order_items i ON o.order_id = i.order_id "
        "WHERE o.order_id = ? GROUP BY o.order_id"
    )
    return query, (order_id.strip(),)
    # generated: copilot — reviewed by: tthavee
